#ifndef MX_TEXTURE_HPP
#define MX_TEXTURE_HPP

#include <QGraphicsScene>
#include <QMediaPlayer>

class MxVideoSurface;
class MxWebView;

class QOpenGLWidget;
class QOpenGLTexture;
class QPixmap;
class QSharedMemory;

class MxTexture : public QObject {
	Q_OBJECT

public:
	// Constructor for texture from file
	MxTexture(QOpenGLWidget *widget, const QString &filePath, QObject *parent = 0);

	// Constructor for shared texture
	MxTexture(QOpenGLWidget *widget, int id, int width, int height, QObject *parent = 0);

	~MxTexture();

	// Bind this texture as current texture used by OpenGL
	void bind();

	// Release this texture from the current texture used by OpenGL
	void release();

	// Activate Shared Texture
	void createSharedTexture(int id, int width, int height);

	// Deactivate Shared Texture
	void destroySharedTexture();

	// Invalidates the shared texture
	bool invalidateSharedTexture();

signals:
	// Signal to emit when texture has loaded / changed
	void invalidate(const QRectF & rect = QRectF(), QGraphicsScene::SceneLayers layers = QGraphicsScene::AllLayers);

private:
	static QStringList IMAGE_SUFFIXES;
	static QStringList VIDEO_SUFFIXES;

	// OpenGL
	QOpenGLWidget *mOpenGLWidget;
	QOpenGLTexture *mOpenGLTexture;

	// WebView
	MxWebView *mWebView;

	// Shared texture data for visuals generated by other programs
	int   mSharedFileDescriptor;
	int * mSharedMemory;
	int   mSharedTextureWidth;
	int   mSharedTextureHeight;

	//
	void prepareWebView();

	// Load image from file path
	void loadImage(const QString &filePath);

	// Load video from file path
	void loadVideo(const QString &filePath);

	// Test if file from filepath is an image
	bool isImage(const QString &filePath);

	// Test if file from filepath is a video
	bool isVideo(const QString &filePath);

private slots:
	void onWebViewFrame();
};

#endif
